# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - func-sentinel-activity-maps

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - '.github/workflows/main_func-sentinel-activity-maps.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './api'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # required for OIDC login
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies into package dir
        run: |
          pip install --target=${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/.python_packages/lib/site-packages -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/requirements.txt

      - name: Zip package
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../func-deploy.zip . -x "*.pyc" -x "*__pycache__*"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_39F253D54E704240BBB48EB8FEEEDB6D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7019E05A2F694C20B817B4DC2F993FD2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9F12F2DB8A674FF3A416688A145F4BCE }}

      - name: Deploy to Azure Functions
        run: |
          az functionapp deploy \
            --resource-group "rg-sentinel-activity-maps" \
            --name "func-sentinel-activity-maps" \
            --src-path func-deploy.zip \
            --type zip
